// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Model
{
    [Table("Product")]
    public partial class Product
    {
        [Key]
        public int Id { get; set; }
        [Column("Product Name")]
        public string Product_Name { get; set; }
        [Column("Product Description")]
        public string Product_Description { get; set; }
        public string Unit { get; set; }
        [Column("Minimum Purchase")]
        public int? Minimum_Purchase { get; set; }
        public string Tags { get; set; }
        public bool? Refundable { get; set; }
        [Column("Purchase Price")]
        public int? Purchase_Price { get; set; }
        [Column("Sale Price")]
        public int? Sale_Price { get; set; }
        [Column("Old Price")]
        public int? Old_Price { get; set; }
        public int? Cat_ID { get; set; }
        [Column("Product Code")]
        [StringLength(50)]
        public string Product_Code { get; set; }
        [Column("Minimum Stock")]
        public int? Minimum_Stock { get; set; }
        public string thumbnail { get; set; }
    }
}