// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Ecommerce.Model;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Ecommerce.Data
{
    public partial class AppDBContext
    {
        private AppDBContextProcedures _procedures;

        public virtual AppDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AppDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public AppDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_GetViewimageRecordResult>().HasNoKey().ToView(null);
        }
    }

    public interface IAppDBContextProceduresContract
    {
        Task<List<SP_GetViewimageRecordResult>> SP_GetViewimageRecordAsync(int? ID, CancellationToken cancellationToken = default);
    }

    public partial class AppDBContextProcedures
    {
        private readonly AppDBContext _context;

        public AppDBContextProcedures(AppDBContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetViewimageRecordResult>> SP_GetViewimageRecordAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetViewimageRecordResult>("EXEC @returnValue = [dbo].[SP_GetViewimageRecord] @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
